feature_extraction:
   mfcc:
      e: True
      De: True
      DDe: True
      coefs: 5
      D: True
      DD: True
   duration: 3.0
   normalize: True

network:
   lstm: [16]
   dense: [16]
   bidirectional: True

training:
   hours_per_epoch: 1
   overlap: 0.5
   batch_size: 1024
   nb_epoch: 1000
   optimizer: rmsprop

testing:
   overlap: 0.25
   binarize:
     onset: 0.5
     offset: 0.5
