workdir: '/vol/work1/bredin/keras/gender/wip'

feature_extraction:
   mfcc:
      e: False
      De: True
      DDe: True
      coefs: 11
      D: True
      DD: True
   duration: 3.2
   normalize: True

embedding:
   output_dim: 8
   lstm: [8, ]
   dense: []
   dropout: 0.0
   bi_directional: False

training:
   margin: 0.2
   per_label: 40
   batch_size: 32
   batch_per_epoch: 100
   nb_epoch: 1000

testing: 
   per_label: 40
   batch_size: 40
