etape: '/Users/bredin/Corpora/etape'
workdir: '/tmp/keras/'

feature_extraction:
   mfcc:
      e: False
      De: True
      DDe: True
      coefs: 11
      D: True
      DD: True
   duration: 2.0
   normalize: True

embedding:
   margin: 0.2
   output_dim: 4
   lstm: [8, ]
   dense: []
   dropout: 0.0
   bidirectional: False

training:
   n_labels_estimate: 120
   triplet:
     n_labels: 40
     per_label: 40
   batch_size: 1560
   nb_epoch: 1000

testing:
   per_label: 40
   batch_size: 40
