etape: '/vol/work1/bredin/corpus/odessa/etape'

feature_extraction:
   mfcc:
      e: False
      De: True
      DDe: True
      coefs: 11
      D: True
      DD: True
   duration: 3.0
   normalize: True

embedding:
   margin: 0.2
   output_dim: 16
   lstm: [16, ]
   dense: [16]
   bidirectional: True
   space: sphere

training:
   n_labels_estimate: 120
   triplet:
     n_labels: 40
     per_label: 40
   batch_size: 1560
   nb_epoch: 1000
   optimizer: rmsprop

testing:
   per_label: 40
   batch_size: 40
